sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

script:
- docker build -t moiamond/ffmpeg-windows-build-helpers:dev-env .

after_success:
  - if [ "$TRAVIS_BRANCH" == "dev-env" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push moiamond/ffmpeg-windows-build-helpers:$TRAVIS_BRANCH;
    fi